package raw.executor

import java.net.{URL, URLClassLoader}

/**
 * Used to load the classes generated by the query compiler. It is important to use the same classloader whenever
 * the query classes are loaded, which includes in the ExecutionServer class and in the Spark executors. Therefore,
 * the same instance of RawMutableURLClassLoader should be used as a parent to the classloader that Spark creates
 * internally (by setting it as Thread.contextClassloader) and by the execution server.
 */
class RawMutableURLClassLoader(parent: ClassLoader, urls: Array[URL] = new Array(0))
  extends URLClassLoader(urls, parent) {

  override def addURL(url: URL): Unit = {
    super.addURL(url)
  }

  override def getURLs(): Array[URL] = {
    super.getURLs()
  }
}

trait RawClassLoader {
  val rawClassLoader = new RawMutableURLClassLoader(this.getClass.getClassLoader)
}